# Generated by Django 3.1.4 on 2020-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.IntegerField(blank=True, max_length=255, null=True)),
                ('introducer', models.DateField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, max_length=255, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('illness', models.CharField(blank=True, max_length=255, null=True)),
                ('explain', models.CharField(blank=True, max_length=255, null=True)),
                ('drug', models.CharField(blank=True, max_length=255, null=True)),
                ('visitdate', models.DateField(blank=True, max_length=255, null=True)),
                ('testresult', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.CharField(blank=True, max_length=255, null=True)),
                ('primarydiagnose', models.CharField(blank=True, max_length=255, null=True)),
                ('needmorevisit', models.CharField(blank=True, max_length=255, null=True)),
                ('needmorevisitdate', models.DateTimeField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
