# Generated by Django 3.1.4 on 2020-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introducer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
