# Generated by Django 3.1.4 on 2020-12-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20201228_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploadimage',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
