# Generated by Django 3.1.4 on 2020-12-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20201229_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploadimage',
        ),
    ]
